services:
  webserver:
    image: nginx:latest
    container_name: nginx-proxy-local
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/conf/app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      language-service-api:
        condition: service_started
      authorization-service-api:
        condition: service_started
      asset-service-api:
        condition: service_started
      printscript-ui:
        condition: service_started
      snippet-service-api:
        condition: service_started
    networks:
      - local-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  printscript-ui:
    container_name: printscript-ui-local
    image: ghcr.io/tef-austral/printscript-ui:dev
    environment:
      VITE_AUTH0_DOMAIN: ${VITE_AUTH0_DOMAIN}
      VITE_AUTH0_CLIENT_ID: ${VITE_AUTH0_CLIENT_ID}
      VITE_AUDIENCE: ${VITE_AUDIENCE}
      VITE_BACKEND_URL: "/api/snippet"
      VITE_AUTH0_URL: "/api/authorization"
      VITE_LANGUAGE_URL: "/api/language"
      VITE_FRONTEND_URL: "http://localhost"
      VITE_DOMAIN: ${VITE_DOMAIN}
      PORT: 5173
    ports:
      - "5173:80"
    networks:
      - local-network
    restart: unless-stopped
    logging: &logging_defaults
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  language-db:
    image: postgres:16
    container_name: language_db_local
    environment:
      POSTGRES_USER: ${POSTGRES_USER_LANGUAGE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_LANGUAGE}
      POSTGRES_DB: ${POSTGRES_DB_LANGUAGE}
    volumes:
      - language_data_local:/var/lib/postgresql/data
    networks:
      - local-network
    restart: unless-stopped
    logging: *logging_defaults

  language-service-api:
    container_name: language-service-api-local
    image: ghcr.io/tef-austral/language-service:dev
    environment:
      SPRING_PROFILES_ACTIVE: development
      SPRING_DATASOURCE_URL: jdbc:postgresql://language-db:5432/${POSTGRES_DB_LANGUAGE}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER_LANGUAGE}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD_LANGUAGE}
      AUTH0_ISSUER_URI: ${AUTH0_ISSUER_URI}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTHORIZATION_SERVICE_URL: http://authorization-service-api:8080
      REDIS_HOST: redis-bus
      REDIS_PORT: 6379
      ASSET_SERVICE_URL: http://asset-service-api:8080/v1/asset
      DB_HOST: language-db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB_LANGUAGE}
      DB_USER: ${POSTGRES_USER_LANGUAGE}
      DB_PASSWORD: ${POSTGRES_PASSWORD_LANGUAGE}
      LANGUAGE_M2M_CLIENT_ID: ${LANGUAGE_M2M_CLIENT_ID}
      LANGUAGE_M2M_CLIENT_SECRET: ${LANGUAGE_M2M_CLIENT_SECRET}
      AUTH0_TOKEN_URI: ${AUTH0_TOKEN_URI}
      NEW_RELIC_APP_NAME: "Language-Service-Local"
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
    depends_on:
      language-db:
        condition: service_started
      authorization-service-api:
        condition: service_started
      redis-bus:
        condition: service_healthy
      asset-service-api:
        condition: service_started
    networks:
      - local-network
    restart: unless-stopped
    logging: *logging_defaults

  authorization-db:
    image: postgres:16
    container_name: authorization_db_local
    environment:
      POSTGRES_USER: ${POSTGRES_USER_AUTHORIZATION}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUTHORIZATION}
      POSTGRES_DB: ${POSTGRES_DB_AUTHORIZATION}
    volumes:
      - authorization_data_local:/var/lib/postgresql/data
    networks:
      - local-network
    restart: unless-stopped
    logging: *logging_defaults

  authorization-service-api:
    container_name: authorization-service-api-local
    image: ghcr.io/tef-austral/authorization-service:dev
    ports:
      - "9090:8080"
    environment:
      SPRING_PROFILES_ACTIVE: development
      SPRING_DATASOURCE_URL: jdbc:postgresql://authorization-db:5432/${POSTGRES_DB_AUTHORIZATION}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER_AUTHORIZATION}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD_AUTHORIZATION}
      AUTH0_ISSUER_URI: ${AUTH0_ISSUER_URI}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_MGMT_CLIENT_ID: ${AUTH0_MGMT_CLIENT_ID}
      AUTH0_MGMT_CLIENT_SECRET: ${AUTH0_MGMT_CLIENT_SECRET}
      NEW_RELIC_APP_NAME: "Authorization-Service-Local"
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
    depends_on:
      authorization-db:
        condition: service_started
    networks:
      - local-network
    restart: unless-stopped
    logging: *logging_defaults

  snippet-service-db:
    image: postgres:16
    container_name: snippet_db_local
    environment:
      POSTGRES_USER: ${POSTGRES_USER_SNIPPET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_SNIPPET}
      POSTGRES_DB: ${POSTGRES_DB_SNIPPET}
    volumes:
      - snippet_data_local:/var/lib/postgresql/data
    networks:
      - local-network
    restart: unless-stopped
    logging: *logging_defaults

  snippet-service-api:
    container_name: snippet-service-api-local
    image: ghcr.io/tef-austral/snippet-service:dev
    ports:
      - "8002:8080"
    environment:
      SPRING_PROFILES_ACTIVE: development
      SPRING_DATASOURCE_URL: jdbc:postgresql://snippet-service-db:5432/${POSTGRES_DB_SNIPPET}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER_SNIPPET}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD_SNIPPET}
      AUTH0_ISSUER_URI: ${AUTH0_ISSUER_URI}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      SNIPPET_SERVICE_M2M_CLIENT_ID: ${SNIPPET_SERVICE_M2M_CLIENT_ID}
      SNIPPET_SERVICE_M2M_CLIENT_SECRET: ${SNIPPET_SERVICE_M2M_CLIENT_SECRET}
      AUTH0_TOKEN_URI: ${AUTH0_TOKEN_URI}
      LANGUAGE_SERVICE_URL: http://language-service-api:8080
      AUTHORIZATION_SERVICE_URL: http://authorization-service-api:8080
      ASSET_SERVICE_URL: http://asset-service-api:8080/v1/asset
      REDIS_HOST: redis-bus
      REDIS_PORT: 6379
      NEW_RELIC_APP_NAME: "Snippet-Service-Local"
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
    depends_on:
      snippet-service-db:
        condition: service_started
      language-service-api:
        condition: service_started
      authorization-service-api:
        condition: service_started
      asset-service-api:
        condition: service_started
      redis-bus:
        condition: service_healthy
    networks:
      - local-network
    restart: unless-stopped
    logging: *logging_defaults

  asset-service-api:
    container_name: "asset_service_local"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_APP_NAME: "Asset-Service-Local"
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_AGENT_ENABLED: "false"
    networks:
      - local-network
    depends_on:
      azurite:
        condition: service_started
    restart: unless-stopped
    logging: *logging_defaults

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite_local"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob_local:/workspace
    networks:
      - local-network
    logging: *logging_defaults

  redis-bus:
    image: redis:7-alpine
    container_name: "redis_bus_local"
    ports:
      - "6379:6379"
    volumes:
      - redis_data_local:/data
    command: redis-server --appendonly yes
    networks:
      - local-network
    restart: unless-stopped
    logging: *logging_defaults
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  language_data_local:
  authorization_data_local:
  snippet_data_local:
  redis_data_local:
  blob_local:

networks:
  local-network:
    driver: bridge